---
title: "Untitled"
format:
 # docx:
  #   reference-doc: modeloTest4.dotx
  #   documentclass: scrreprt
  #   classoption: nottoc
  #   toc: true
  #   toc-depth: 3
  #   lof: true
  #   lot: true
  #   loe: true
  #   include-in-header: 
  #     text: |
  #       \usepackage{tocbibind}
  pdf:
    documentclass: scrreprt
    classoption: nottoc
    toc: true
    toc-depth: 3
    lof: true
    lot: true
    loe: true
    include-in-header:
      text: |
        \usepackage{tocbibind}
 
editor: visual
execute: 
  echo: false
  warning: false
lang: pt
number-sections: true

---

```{r}

library(knitr)
library(kableExtra)
library(tidyverse)
library(officer)


```

# Lista de tabelas

1. [@tbl-iris]
2. [@tbl-mtcars]


# Lista de Equações

1. [@eq-return]
2. [@eq-portfolioReturn]


# as mudanças



$$
R = log(r_{i,t}) - log(r_{i,t - 1})
$$ {#eq-return}

$$
 R_{p} = \sum_{t = 1}^{N}i_{t}w_{t}
$$ {#eq-portfolioReturn}

```{r}
#| label: tbl-iris
#| tbl-cap: tabela ires
knitr::kable(head(iris)) 
```

```{r}
#| label: tbl-mtcars
#| tbl-cap: tabela mtcars
knitr::kable(head(mtcars)) 
```
