---
title: "outputFigs"
author: "Matheus"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=999)
library(tidyverse)
library(quantmod)
library(scales)
library(PerformanceAnalytics)
library(openxlsx)
library(gt)

symbols = c("BTC-USD","ETH-USD","USDC-USD", "USDT-USD", "BNB-USD", "XRP-USD", "ADA-USD","DOGE-USD","SOL-USD","MATIC-USD")
asset_return_long = read.xlsx("outputData/dataAssetReturn.xlsx")
possibilities = read.xlsx("outputData/dataPossibilities.xlsx") %>% mutate_all(~as.numeric(.x))

min_var <- possibilities[which.min(possibilities$sd),]
max_sr <- possibilities[which.max(possibilities$sharpeRatePortfolio),]
max_re <- possibilities[which.max(possibilities$mean),]

```

# Graficos

```{r graph 1}

possibilities %>%
  ggplot(aes(x = sd, y = mean, color = sharpeRatePortfolio)) +
  geom_point() +
  theme_classic() +
  scale_y_continuous(labels = scales::percent) +
  scale_x_continuous(labels = scales::percent) +
  labs(x = 'Risco',
       y = 'Retorno esperado',
       title = "Optimização de portfolio & Fronteira eficiente",
       colour = "Indice sharpe") +
  geom_point(aes(x = sd,
                 y = mean), data = min_var, color = 'red') +
  geom_point(aes(x = sd,
                 y = mean), data = max_sr, color = 'red') +
  geom_text(x=min_var$sd, y = min_var$mean + .0002,label="Menor risco", color = "red", size=2) +
  geom_text(x=max_sr$sd, y = max_sr$mean + .0002,label="Maior indice sharpe", color = "red",size=2 ,check_overlap = T) +
  theme_bw() +
  theme( plot.title = element_text(hjust = .5))

```

```{r graph2}

asset_return_long %>%
  group_by(asset) %>%
  summarise(sd= sd(returns), mean= mean(returns)) %>%
  ggplot(aes(x=sd,y=mean,color=asset)) +
  geom_point(size=1, show.legend = FALSE) + 
  #scale_y_continuous() +
  scale_x_continuous(labels = scales::percent) +
  labs(y="Retorno esperado",
       x="Risco",
       colour="Ativo",
       title = "Risco x Retorno") +
  geom_text(aes(label = asset, y = mean + .0002), check_overlap = FALSE, size=3) +
  theme_bw() +
  theme(legend.position="none", plot.title = element_text(hjust = .5))

```

# Tabelas

```{r tb1}
possibilities %>% 
  arrange(sharpeRatePortfolio) %>% 
  head() %>% 
  gt() %>% 
  tab_header(title = "top 5 combinações com piores indices sharpe") %>%
  fmt_percent(columns = symbols,decimals = 0, dec_mark = ",", sep_mark = ".") %>%
  fmt_percent(columns = c(sharpeRatePortfolio,sd),decimals = 3, dec_mark = ",", sep_mark = "." ) %>%
  fmt_number(columns = mean, decimals = 4) %>%
  cols_label(sharpeRatePortfolio = "Indice Sharpe", sd= "Risco", mean = "Retorno esperado")
```

</br>

```{r tb2}
possibilities %>% 
  arrange(desc(sharpeRatePortfolio)) %>% 
  head() %>% 
  gt() %>% 
  tab_header(title = "top 5 combinações com melhores indices sharpe") %>%
  fmt_percent(columns = symbols,decimals = 0, dec_mark = ",", sep_mark = ".") %>%
  fmt_percent(columns = c(sharpeRatePortfolio,sd),decimals = 3, dec_mark = ",", sep_mark = "." ) %>%
  fmt_number(columns = mean, decimals = 4) %>%
  cols_label(sharpeRatePortfolio = "Indice Sharpe", sd= "Risco", mean = "Retorno esperado")
```
