---
title: "test"
format: 
  docx:
    reference-doc: "ModeloTCC8.dotx"
editor: visual
execute: 
  echo: false
  warning: false
---
## test

```{r}
#| label: start

library(tidyverse)
library(knitr)
library(gt)
```

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

```{r}
#| label: fig-f1
#| fig-cap: f1
#| fig-width: 5.75
#| fig-height: 5



mtcars %>% ggplot(aes(x=cyl,y = mpg)) + geom_col()



```

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

```{mermaid}
%%| fig-width: 5.75
%%| fig-height: 5

flowchart TD
 a([Obtenção de dados]) ---|Selic| b[rbcb] 
 a ---|criptomoedas | c[quantmod] 
 b & c --> d[Transformação]
 d --> e[tidyverse] & f[base] & g[PerformanceAnalytics]
 e & f & g --> h{Resultado}
 h --> i[Grafico] & j[Tabela]
 i --> k[tidyverse] & l[corrplot] & m[RColorBrewer]
 j --> n[tidyverse] & o[knitr]
  
```


```{r}
#| label: tbl-t1
#| tbl-cap: tbl


kable(mtcars %>% head())



```



```{r}
#| label: tbl-t2
#| tbl-cap: tbl2


mtcars %>% 
  head() %>% 
  gt(process_md = T)



```


